export const WORDS = [
    "APPLE", "BEACH", "CHAIR", "DANCE", "EAGLE", "FLAME", "GRAPE", "HOUSE", "IMAGE", "JELLY",
    "KITE", "LEMON", "MANGO", "NIGHT", "OCEAN", "PIANO", "QUEEN", "RIVER", "STORM", "TABLE",
    "UMBRELLA", "VOICE", "WATER", "XYLOPHONE", "YACHT", "ZEBRA"
  ];